name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Sets up Node.js (adjust version if needed)

      - name: Install dependencies
        run: npm install  # Install project dependencies (if you have a package.json)

      - name: Build project
        run: npm run build  # Run build command (adjust if needed)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
          publish_dir: ./public  # Directory to publish (adjust if needed)

